### ISSUE TITLE
Typo 😎

### ISSUE THREAD

**Issue by jogboms** [jlooper/cleanweather#1]
Incorrect closing tag 
https://github.com/jlooper/cleanweather/blob/24df68c202728dcab4effd4e2445309f40a0a126/app/app.js#L39

Needs a closing tag here
https://github.com/jlooper/cleanweather/blob/24df68c202728dcab4effd4e2445309f40a0a126/app/app.js#L53

**Comment by jlooper** [comment]
woops! thanks!
